resize_shape: [224, 224]
targets: ['balcony', 'bathroom', 'bedroom', 'dining room', 'exterior', 'gym_sports', 'kitchen', 'living room', 'empty room', 'stairs', 'study_room','Swimming pool','utility room']
model_path: "keras_model.h5"
model_url: "https://drive.google.com/file/d/19TsvZ96FhSg2vcm0Eulg-H0wrGeC5IkR/view?usp=sharing"
model_sha256: "e88c0d959f65d491428ed308644c00173d8920bcf42660ad6b5a1af1f251619b "